### ISSUE TITLE
Document why `Data.Metrology.Linear` wants `Qu` on the outside

### ISSUE THREAD

**Issue by ocharles** [goldfirere/units#55]
Hi, bit of an odd "issue", but please bear with me!

We've just started using `units` in a computer vision application, and almost all the measurements we have are two-dimensional vectors. Looking at https://github.com/goldfirere/units/blob/master/Tests/Compile/Simulator.hs, it's clear that the intention is to represent entire vectors an quantities, but it felt more natural for us (when using `linear`) to have `Qu` under the vector itself. That is...

``` haskell
velocity :: V2 Length
```

Is there a fundamental reason why this is a bad idea? It seems that with this approach, `Data.Metrology.Linear` isn't necessary at all (except for maybe providing a few orphan instances), as `Linear` is already sufficiently polymorphic to support `units`.

**Comment by goldfirere** [comment]
I'm glad `units` is seeing some action in the field!

To answer your question: I don't know enough to answer, not being familiar with `linear`. `Data.Metrology.Linear` is a contribution from a user, and I have not thought deeply about correctness implications of it all (other than that it generally looks correct). You say `units` would need some orphan instances. What would these be? Could these instances be abused to defeat the guarantees provided by `units`?

Note that you can always experiment with an idea like this by importing `Data.Metrology.Unsafe` and writing instances yourself.

In any case, if we figure out the right answer here, I'm happy to include these instances within `units`.

**Comment by ocharles** [comment]
Thanks for the quick reply! I'm not entirely sure which instances would be require, I was just thinking out loud as `linear` defines some classes like `Affine` (though these are `* -> *` and are more properties of the containers such as `V3`, rather than the objects within the vector spaces). @hesiod - it looks like you wrote `Data.Metrology.Linear` - could you clarify why it's necessary?

**Comment by hesiod** [comment]
Hi @ocharles, glad you found the way to `units` - I already had a smile on my face when you tweeted about it on thursday! (On a more personal note, I'm a big fan of your blog, keep up the good work!)

I personally started out using the `Data.Metrology.Vector` interface, but when I later discovered the `linear` package I wanted to use it with `units`. I started out by replacing the function definitions one-by-one to form `Data.Metrology.Linear`. IIRC, the higher-kinded type classes in `linear` also simplified some things. But since I just adapted the structure from the `vector-space`-based module, I didn't really think about the `Vector (Qu d l n)` vs `Qu d l Vector` question.

It has been some time since I wrote the module in question, but my intuition says that `V3 (Qu d l n)` is a vector of quantities, whereas you actually want a quantity that happens to have more than one dimension, i.e. is represented by a vector.

I tried out for fun how a `V2 Length` would behave and noticed the following:

 - To convert the vector back to a dimensionless quantity, you'll have to use the rather unidiomatic `fmap (# Meter)` instead of just `# Meter`:
```Haskell
λ> (V2 0 0 % Meter) # Meter
<warning about defaulting omitted>
V2 0.0 0.0
λ> fmap (# Meter) (V2 (0 % Meter) (0 % Meter) :: V2 Length) 
V2 0.0 0.0
```
   Also note the repeated `% Meter`.
 - But most importantly, this:
```Haskell
λ> qd (V2 (0 % Meter) (0 % Meter) :: V2 Length) 

<interactive>:30:1:
    Couldn't match type ‘'['F Length One]’ with ‘'[]’
<snip>
```
Reason for this is the constraint `d ~ '[]` in the [derived `Num` instance](https://github.com/goldfirere/units/blob/master/Data/Metrology/Qu.hs#L234)

Please bear with me if I made any mistakes - I'm not really sure if this is the right reasoning behind `Qu d l Vector`.

**Comment by goldfirere** [comment]
This issue has not gotten any action in some time. Closing -- but do reopen if there is a redesign to be considered.
